SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Table_05867](
	[id] [int] NOT NULL,
	[description] [text] COLLATE Latin1_General_CI_AS NULL,
	[column00000] [int] NULL,
	[column00001] [int] NULL,
	[column00002] [int] NULL,
 CONSTRAINT [PK_Table_05867] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)

GO
